name: Daily Commit

on:
  schedule:
    - cron: "30 2 * * *"  # Runs daily at 02:30 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git (21f2001412@ds.study.iitm.ac.in)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "21f2001412@ds.study.iitm.ac.in"

      - name: Make a change
        run: |
          echo "Last run: $(date)" > last_run.txt
          git add last_run.txt

      - name: Commit and push changes
        run: |
          git commit -m "Automated commit from GitHub Actions [$(date)]" || exit 0
          git push
